using EventBusExplorer.Server.Application.ServiceBroker.Abstractions;

namespace EventBusExplorer.Server.Infrastructure.RabbitMQ;

public class RabbitMQTopicsService : IServiceBrokerTopicsService
{
    private readonly RabbitMQAdministrationClient _adminClient;
    private readonly RabbitMQClient _client;

    public RabbitMQTopicsService(
        RabbitMQAdministrationClient adminClient,
        RabbitMQClient client
    )
    {
        _adminClient = adminClient;
        _client = client;
    }

    public async Task<string> CreateTopicAsync(string? name, CancellationToken cancellationToken = default)
    {
        await _adminClient.CreateExchangeAsync(
            name,
            type: ExchangeType.Fanout,
            cancellationToken: cancellationToken);

        //
        // Since exchange creation through management API does not return anything,
        // It is assumed that if the request is successful then the exchange has been created.
        //
        return name!;
    }

    public async Task<IList<string>> GetTopicsAsync(CancellationToken cancellationToken = default)
    {
        IList<Exchange> topicExchanges = await _adminClient.GetExchangesAsync(
            type: ExchangeType.Fanout,
            cancellationToken: cancellationToken);

        return topicExchanges.Select(x => x.Name).ToList();
    }

    public async Task<string> GetTopicAsync(string name, CancellationToken cancellationToken = default)
    {
        Exchange? topic = await _adminClient.GetExchangeAsync(
            name,
            type: ExchangeType.Fanout,
            cancellationToken: cancellationToken);

        if (topic is null)
            throw new Exception($"Cannot find exchange with name: {name}"); //TODO: define or find a suitable exc type

        return topic.Name;
    }

    public async Task DeleteTopicAsync(string name, CancellationToken cancellationToken = default)
    {
        await _adminClient.DeleteExchangeAsync(name, cancellationToken: cancellationToken);
    }

    public async Task<IList<string>> GetSubscriptionsAsync(string topicName, CancellationToken cancellationToken = default)
    {
        return await _adminClient.GetQueuesAsync(topicName, cancellationToken: cancellationToken);
    }

    public async Task<string> GetSubscriptionAsync(string topicName, string subscriptionName, CancellationToken cancellationToken = default)
    {
        return await _adminClient.GetQueueAsync(subscriptionName, topicName, cancellationToken: cancellationToken);
    }

    public Task<string> CreateSubscriptionAsync(string topicName, string? name, CancellationToken cancellationToken = default)
    {
        // Subscription name is autogenerated if input in empty.
        name = _client.CreateQueueAndBindToExchange(queueName: name, exchangeName: topicName);
        return Task.FromResult(name);
    }

    public Task DeleteSubscriptionAsync(string topicName, string subscriptionName, CancellationToken cancellationToken = default)
    {
        _client.DeleteQueue(queueName: subscriptionName, exchangeName: topicName);
        return Task.CompletedTask;
    }
}
