name: EventBusExplorer

on:
  push:
    branches: [Krusty93/issue25]
    paths:
      - src/Server/**

jobs:

  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          flowesb/event-bus-explorer
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref
          type=sha
        labels:
          org.opencontainers.image.title=event-bus-explorer
          org.opencontainers.image.description=EventBusExplorer build
          org.opencontainers.image.authors=FloweSB
          org.opencontainers.image.url=github.com/FloweSB

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile
