name: EventBusExplorer (PR)

on:
  pull_request:
    branches: [main]
    paths:
      - src/Server/*
      - .github/workflows/server_pr.yml

jobs:

  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src/Server/EventBusExplorer.Server.API

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET 7 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: |
        dotnet restore \
          --verbosity minimal

    - name: Build
      run: |
        dotnet build \
          --no-restore \
          --configuration Release
