name: EventBusExplorer

on:
  push:
    branches: [main]
    paths:
      - src/Server/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Login to ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=sha
          latest
        labels:
          org.opencontainers.image.title=${{ github.repository }}
          org.opencontainers.image.description=EventBusExplorer build
          org.opencontainers.image.authors=FloweSB
          org.opencontainers.image.url=github.com/FloweSB/${{ github.repository }}

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
